spring:
  datasource:
    url: jdbc:mysql://localhost:3306/huilan?useSSL=false
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root

  redis:
    host: 43.139.125.20
    password: 123456
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8081
  servlet:
    context-path: /huilan

mybatis-plus:
  type-aliases-package: com.xiaomaotongzhi.huilan.entity
  mapper-locations: classpath:mappers/*.xml

wechat:
  appid: wx80603a3fea2bfc4b
  secret: 92981ea58e9bb63f11a7373923176e40
