spring:
  datasource:
    url: jdbc:mysql://localhost:3306/huilan?useSSL=false
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    datasource:
      max-activity: 1000
      max-idle: 20
      min-idle: 5
      initial-size: 10

  redis:
    host: 43.139.125.20
    password: 123456
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8081
  servlet:
    context-path: /huilan

mybatis-plus:
  type-aliases-package: com.xiaomaotongzhi.huilan.entity
  mapper-locations: classpath:mappers/*.xml

wechat:
  appid: wx9ee81b2bc09f089e
  secret: 5fb9d2d43d923f5758b31981b3a9b35c
